### ISSUE TITLE
Wrong link in the readme

### ISSUE THREAD

**Issue by blackdahlia** [OpenBankingUK/read-write-api-specs#44]
### Problem

File: `./README.md`

```markdown
...
### Payment Initiation

- [Swagger (OpenAPI 2.0) - YAML](./dist/swagger/confirmation-funds-swagger.yaml)
...
```
### Description
The link above should refer to `./dist/swagger/payment-initiation-swagger.yaml`.

**Comment by jmatospob** [comment]
Hi, thanks for this, I'll have a look today.

**Comment by jmatospob** [comment]
Fixed
